In [1]:
import numpy as np
import pandas as pd 


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_selection import f_classif
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import ExtraTreesRegressor  # Import ExtraTreesRegressor class
from sklearn.preprocessing import MinMaxScaler

In [2]:

# Specify the file path
file_path = r"C:\Users\chimi\Desktop\Python Data Science Projects\airbnb-rentalprice\task5-featureengineering\athens_rentalfinaldata_2.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(df.head())

   listing_id                                               name  host_id  \
0       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
1       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
2       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
3       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
4       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177

  neighbourhood  latitude  longitude        room_type  price  minimum_nights  \
0   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
1   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
2   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
3   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
4   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1

   number_of_reviews  ... bedrooms  beds  baths  MinDisplacement  \
0                 41  ...      3.0   5.0    2.0         0.684065
1                 41  ...      3.0   5.0    2.0         0.684065
2                 41  ...      3.0   5.0    2.0         0.684065
3                 41  ...      3.0   5.0    2.0         0.684065
4                 41  ...      3.0   5.0    2.0         0.684065

   NearestStation  IsHoliday holidayDateDiff nearestHoliday sentiment  \
0     Αμπελόκηποι      False            3879       New year  0.547333
1     Αμπελόκηποι      False            3426       New year  0.366171
2     Αμπελόκηποι      False            2799       New year  0.260238
3     Αμπελόκηποι      False            3148       New year  0.512778
4     Αμπελόκηποι      False              19    Whit Monday  0.387778

  FemalePref
0          0
1          0
2          0
3          0
4          0

[5 rows x 31 columns]

In [3]:
df.head(5)

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,...,bedrooms,beds,baths,MinDisplacement,NearestStation,IsHoliday,holidayDateDiff,nearestHoliday,sentiment,FemalePref
0,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,3.0,5.0,2.0,0.684065,Αμπελόκηποι,False,3879,New year,0.547333,0
1,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,3.0,5.0,2.0,0.684065,Αμπελόκηποι,False,3426,New year,0.366171,0
2,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,3.0,5.0,2.0,0.684065,Αμπελόκηποι,False,2799,New year,0.260238,0
3,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,3.0,5.0,2.0,0.684065,Αμπελόκηποι,False,3148,New year,0.512778,0
4,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,3.0,5.0,2.0,0.684065,Αμπελόκηποι,False,19,Whit Monday,0.387778,0

In [4]:
df.isnull().mean()

listing_id                        0.000000
name                              0.000000
host_id                           0.000000
neighbourhood                     0.000000
latitude                          0.000000
longitude                         0.000000
room_type                         0.000000
price                             0.000000
minimum_nights                    0.000000
number_of_reviews                 0.000000
last_review                       0.000000
reviews_per_month                 0.000000
calculated_host_listings_count    0.000000
availability_365                  0.000000
number_of_reviews_ltm             0.000000
reviewer_id                       0.000000
date                              0.000000
comments                          0.000000
property_type                     0.000000
city                              0.000000
rating                            0.000000
bedrooms                          0.000000
beds                              0.000000
baths                             0.000000
MinDisplacement                   0.000000
NearestStation                    0.036579
IsHoliday                         0.000000
holidayDateDiff                   0.000000
nearestHoliday                    0.000000
sentiment                         0.000000
FemalePref                        0.000000
dtype: float64

In [5]:
mode_value = df['NearestStation'].mode()[0]

# Fill missing values with the mode
df['NearestStation'].fillna(mode_value, inplace=True)

In [6]:
df.isnull().sum()

listing_id                        0
name                              0
host_id                           0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
reviewer_id                       0
date                              0
comments                          0
property_type                     0
city                              0
rating                            0
bedrooms                          0
beds                              0
baths                             0
MinDisplacement                   0
NearestStation                    0
IsHoliday                         0
holidayDateDiff                   0
nearestHoliday                    0
sentiment                         0
FemalePref                        0
dtype: int64

In [7]:
df.columns

Index(['listing_id', 'name', 'host_id', 'neighbourhood', 'latitude',
       'longitude', 'room_type', 'price', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'reviewer_id', 'date', 'comments',
       'property_type', 'city', 'rating', 'bedrooms', 'beds', 'baths',
       'MinDisplacement', 'NearestStation', 'IsHoliday', 'holidayDateDiff',
       'nearestHoliday', 'sentiment', 'FemalePref'],
      dtype='object')

In [8]:
# Encode categorical variables

def one_hot_encode_column(df, column_name):
    """One-hot encodes a specified column of a dataframe."""
    # Label encoding
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(df[column_name].fillna(""))

    # OneHot encoding
    onehot_encoder = OneHotEncoder(sparse=False)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded.reshape(-1, 1))

    # Constructing column names for one-hot encoded columns
    onehot_cols = [f"{column_name}_{cls}" for cls in label_encoder.classes_]
    
    return pd.DataFrame(onehot_encoded, columns=onehot_cols)

df_cat = df[['neighbourhood', 'room_type', 'property_type', 'NearestStation', 'IsHoliday', 'nearestHoliday']]

# Using the function to one-hot encode each column
for cols in df_cat.columns:
    df_encoded = one_hot_encode_column(df_cat, cols)
    df_cat = pd.concat([df_cat, df_encoded], axis=1)
    df_cat.drop(cols, axis=1, inplace=True)

# Adding the 'price' column after the loop
df_cat = pd.concat([df['price'], df_cat], axis=1)

C:\Users\chimi\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\chimi\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\chimi\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\chimi\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\chimi\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\chimi\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [9]:
df_cat.head(5)

,price,neighbourhood_1Ο ΝΕΚΡΟΤΑΦΕΙΟ,neighbourhood_ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ,neighbourhood_ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ,neighbourhood_ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ,neighbourhood_ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ,neighbourhood_ΑΚΡΟΠΟΛΗ,neighbourhood_ΑΜΠΕΛΟΚΗΠΟΙ,neighbourhood_ΑΝΩ ΚΥΨΕΛΗ,neighbourhood_ΑΝΩ ΠΑΤΗΣΙΑ,...,nearestHoliday_Easter Monday,nearestHoliday_Easter Sunday,nearestHoliday_Epiphany,nearestHoliday_Glorifying Mother of God,nearestHoliday_Good Friday,nearestHoliday_Labour Day,nearestHoliday_New year,nearestHoliday_Ohi Day,nearestHoliday_Pentecost,nearestHoliday_Whit Monday
0,200,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,200,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,200,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,200,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,200,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [10]:
columns = ['listing_id','host_id','reviewer_id','review_id']

for col in columns:
    if col in df.columns:
        print(f"Unique values for {col}:")
        print(len(df[col].unique()))  # Added the missing parenthesis here
    else:
        print(f"Column '{col}' does not exist in the DataFrame.")

Unique values for listing_id:
9751
Unique values for host_id:
4655
Unique values for reviewer_id:
461221
Column 'review_id' does not exist in the DataFrame.

In [11]:
# Too many unqiue values drop the columns
df.drop(columns=['listing_id','host_id','reviewer_id'], axis=1, inplace=True)

In [12]:
# Drop dates
df.drop(columns=['last_review','date'],axis=1, inplace=True)

In [13]:
# Drop coordinates
df.drop(['latitude','longitude'], axis=1, inplace=True)

In [14]:
# Drop texts columns
df.drop(columns=['comments','name'],axis=1, inplace=True)

In [15]:
df['FemalePref'].value_counts()

0    461221
Name: FemalePref, dtype: int64

In [16]:
# Drop FemalePref - filled with 0
df.drop('FemalePref', axis=1, inplace=True)

In [17]:
# Calculate correlation
correlation = df[['price','minimum_nights','number_of_reviews','reviews_per_month',
                  'calculated_host_listings_count', 'availability_365',
                  'number_of_reviews_ltm','rating','bedrooms','beds',
                  'baths','MinDisplacement','holidayDateDiff','sentiment']].corr(method='pearson')

# To visualize styled DataFrame in Jupyter notebook (or another interactive environment):
styled_correlation = correlation.style.background_gradient(cmap='coolwarm')
display(styled_correlation)  # Use this line if you're in a Jupyter environment

# Save the raw correlation matrix to an Excel file
correlation.to_excel('continuousPearsonLinear.xlsx', index = False)

C:\Users\chimi\AppData\Local\Temp\ipykernel_9408\3192580514.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation = df[['price','minimum_nights','number_of_reviews','reviews_per_month',

In [25]:
# What are the top 5 highly correleated variables in releation to price?

# Select correlations with 'price' and exclude the self-correlation
correlation_with_price = correlation['price'].drop('price')

# Sort in descending order and print the top 5
top_5_correlations = correlation_with_price.sort_values(ascending=False).head(5)
print(top_5_correlations)

baths                             0.496323
bedrooms                          0.467559
beds                              0.430461
calculated_host_listings_count    0.120061
availability_365                  0.105670
Name: price, dtype: float64

In [26]:
# Spearman correleation
correlation = df[['price','minimum_nights','number_of_reviews','reviews_per_month',
                  'calculated_host_listings_count', 'availability_365',
                  'number_of_reviews_ltm','rating','bedrooms','beds',
                  'baths','MinDisplacement','holidayDateDiff','sentiment']].corr(method='spearman')

# To visualize styled DataFrame in Jupyter notebook (or another interactive environment):
styled_correlation = correlation.style.background_gradient(cmap='coolwarm')
display(styled_correlation)  # Use this line if you're in a Jupyter environment

# Save the raw correlation matrix to an Excel file
correlation.to_excel("continuousPearsonLinear.xlsx", index = False)

C:\Users\chimi\AppData\Local\Temp\ipykernel_23344\3717852437.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation = df[['price','minimum_nights','number_of_reviews','reviews_per_month',

In [27]:
correleation_with_price =  correlation['price'].drop('price')
top_5_correleation = correlation_with_price.sort_values(ascending=False).head(5)
print(top_5_correleation)

baths                             0.496323
bedrooms                          0.467559
beds                              0.430461
calculated_host_listings_count    0.120061
availability_365                  0.105670
Name: price, dtype: float64

In [28]:
# Top 15 Kendall correleation(linear)
print('Amount of categorical variable: {}'.format(len(df_cat.keys())))

Amount of categorical variable: 111

In [ ]:
df_cat.corr(method='kendall')['price'].sort_values(ascending=False)[1:20].to_csv('categoricalKendalTop10.csv', index=True)
df_cat.corr(method='kendall')['price'].sort_values(ascending=False)[1:20]

C:\Users\chimi\anaconda3\lib\site-packages\scipy\stats\stats.py:4812: RuntimeWarning: overflow encountered in longlong_scalars
  (2 * xtie * ytie) / m + x0 * y0 / (9 * m * (size - 2)))
C:\Users\chimi\anaconda3\lib\site-packages\scipy\stats\stats.py:4814: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(var) / np.sqrt(2)))
C:\Users\chimi\anaconda3\lib\site-packages\scipy\stats\stats.py:4812: RuntimeWarning: overflow encountered in longlong_scalars
  (2 * xtie * ytie) / m + x0 * y0 / (9 * m * (size - 2)))
C:\Users\chimi\anaconda3\lib\site-packages\scipy\stats\stats.py:4814: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(var) / np.sqrt(2)))

In [18]:
# ANOVA
X = df_cat.drop(columns=["price"])  # Simpler way to exclude "price"
y = df_cat["price"]

# Check if 'price' is categorical, if not, raise a warning
if y.nunique() > 20:  # Assuming a threshold of 20 unique values for a variable to be considered continuous
    print("Warning: 'price' seems to be a continuous variable. Consider using f_regression instead.")

anova_f = f_classif(X, y)

# Simplifying the joining and sorting process
sorted_features = sorted(zip(anova_f[0], X.columns), reverse=True)

print("Top 10 F-Value:")
for f_value, col_name in sorted_features[:15]:  # Adjusted to top 10
    print("{}: {}".format(col_name, f_value))

Warning: 'price' seems to be a continuous variable. Consider using f_regression instead.
Top 10 F-Value:
property_type_Villa: 1780.577681023933
property_type_Boutique hotel: 1152.8425641506738
room_type_Entire home/apt: 460.52081091140127
room_type_Private room: 453.4235454457228
neighbourhood_ΖΑΠΠΕΙΟ: 361.9404198664433
property_type_Townhouse: 303.05179683921335
property_type_Home: 302.09867027274464
NearestStation_Ακρόπολη: 275.7451889945117
property_type_Floor: 250.5029069951296
NearestStation_Μοναστηράκι: 236.50343772493105
NearestStation_Σύνταγμα: 232.88103058461832
neighbourhood_ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ: 218.85592471135809
room_type_Shared room: 203.08421914542964
neighbourhood_ΑΚΡΟΠΟΛΗ: 202.16159465249447
property_type_Loft: 181.03049599278486

In [19]:
sorted_df = pd.DataFrame(sorted_features).iloc[:15].to_csv('categoricalANOVANonLinerTop15.csv', index=False)

In [20]:
sorted_features

[(1780.577681023933, 'property_type_Villa'),
 (1152.8425641506738, 'property_type_Boutique hotel'),
 (460.52081091140127, 'room_type_Entire home/apt'),
 (453.4235454457228, 'room_type_Private room'),
 (361.9404198664433, 'neighbourhood_ΖΑΠΠΕΙΟ'),
 (303.05179683921335, 'property_type_Townhouse'),
 (302.09867027274464, 'property_type_Home'),
 (275.7451889945117, 'NearestStation_Ακρόπολη'),
 (250.5029069951296, 'property_type_Floor'),
 (236.50343772493105, 'NearestStation_Μοναστηράκι'),
 (232.88103058461832, 'NearestStation_Σύνταγμα'),
 (218.85592471135809, 'neighbourhood_ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ'),
 (203.08421914542964, 'room_type_Shared room'),
 (202.16159465249447, 'neighbourhood_ΑΚΡΟΠΟΛΗ'),
 (181.03049599278486, 'property_type_Loft'),
 (176.1093785674817, 'neighbourhood_ΘΗΣΕΙΟ'),
 (176.08889495870304, 'property_type_cycladic house'),
 (166.2148432485083, 'property_type_Serviced apartment'),
 (159.87285773862325, 'neighbourhood_ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ'),
 (158.21802528398328, 'NearestStation_Σταθμός Λαρίσης'),
 (155.01254901336344, 'NearestStation_Αριστίππου'),
 (153.7042028054306, 'room_type_Hotel room'),
 (133.8247639520491, 'neighbourhood_ΚΟΛΩΝΑΚΙ'),
 (132.91675323894944, 'NearestStation_Θησείο'),
 (132.02935182410613, 'property_type_Rental unit'),
 (124.74335501871016, 'neighbourhood_ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ'),
 (120.50205397568148, 'neighbourhood_ΓΚΑΖΙ'),
 (115.67100605976275, 'neighbourhood_ΚΕΡΑΜΕΙΚΟΣ'),
 (112.6798596868144, 'neighbourhood_ΛΥΚΑΒΗΤΤΟΣ'),
 (112.38436187114138, 'property_type_Hostel'),
 (111.320963678239, 'NearestStation_Συγγρού-Φιξ'),
 (110.45257643641014, 'NearestStation_Βικτώρια'),
 (108.7434272500609, 'NearestStation_Κεραμεικός'),
 (103.28231674979891, 'property_type_Earthen home'),
 (102.655654971755, 'neighbourhood_ΣΤΑΔΙΟ'),
 (101.37072119059061, 'neighbourhood_ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ'),
 (99.829087011841, 'property_type_Condo'),
 (99.21197730047236, 'neighbourhood_ΚΥΨΕΛΗ'),
 (98.5776373695646, 'neighbourhood_1Ο ΝΕΚΡΟΤΑΦΕΙΟ'),
 (98.19760195219244, 'neighbourhood_ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ'),
 (96.82291559848288, 'NearestStation_Ομόνοια'),
 (96.02562056795524, 'NearestStation_Μεταξουργείο'),
 (93.80624328183423, 'neighbourhood_ΝΕΟΣ ΚΟΣΜΟΣ'),
 (92.98735430392705, 'NearestStation_Πανεπιστήμιο'),
 (83.35920424531257, 'property_type_Guest suite'),
 (80.3881661126395, 'NearestStation_Άγιος Ιωάννης'),
 (77.02903994996937, 'property_type_Vacation home'),
 (72.76094401237391, 'property_type_Tiny home'),
 (70.34085807908171, 'NearestStation_Αμπελόκηποι'),
 (69.75710238915877, 'neighbourhood_ΡΙΖΟΥΠΟΛΗ'),
 (68.81445557778049, 'neighbourhood_ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ'),
 (67.5224186935064, 'NearestStation_Ευαγγελισμός'),
 (67.13578520431028, 'neighbourhood_ΝΙΡΒΑΝΑ'),
 (66.48978448879988, 'property_type_Aparthotel'),
 (65.77970794026733, 'NearestStation_Νέος Κόσμος'),
 (64.81922562692633, 'neighbourhood_ΠΕΔΙΟ ΑΡΕΩΣ'),
 (64.60836972756783, 'neighbourhood_ΚΟΛΩΝΟΣ'),
 (63.722929493854394, 'neighbourhood_ΠΑΓΚΡΑΤΙ'),
 (62.906298137954344, 'neighbourhood_ΓΟΥΒΑ'),
 (61.094838978229376, 'neighbourhood_ΠΕΤΡΑΛΩΝΑ'),
 (57.40878734301478, 'neighbourhood_ΒΟΤΑΝΙΚΟΣ'),
 (55.642358406625966, 'NearestStation_Πετράλωνα'),
 (55.632003677428344, 'neighbourhood_ΑΜΠΕΛΟΚΗΠΟΙ'),
 (51.54039126520947, 'property_type_Nature lodge'),
 (49.041460695543556, 'neighbourhood_ΓΟΥΔΙ'),
 (48.68982947454367, 'neighbourhood_ΠΑΤΗΣΙΑ'),
 (48.0169131443084, 'NearestStation_Άγιος Γεώργιος'),
 (46.09068357931946, 'neighbourhood_ΓΚΥΖΗ'),
 (45.7256382413649, 'NearestStation_Μέγαρο Μουσικής'),
 (45.26895179424244, 'neighbourhood_ΙΛΙΣΙΑ'),
 (39.15261400818965, 'property_type_Hotel'),
 (37.001381766668025, 'nearestHoliday_New year'),
 (35.5793908357845, 'neighbourhood_ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ'),
 (31.49111519143782, 'property_type_Place to stay'),
 (27.561075254390552, 'neighbourhood_ΣΤΑΘΜΟΣ ΛΑΡΙΣΗΣ'),
 (27.363512368914538, 'neighbourhood_ΑΝΩ ΚΥΨΕΛΗ'),
 (27.351138146257668, 'neighbourhood_ΠΛΑΤΕΙΑ ΑΜΕΡΙΚΗΣ'),
 (22.90208368230512, 'NearestStation_Ρουφ'),
 (22.53971740989192, 'property_type_Guesthouse'),
 (20.455924387034006, 'neighbourhood_ΠΕΝΤΑΓΩΝΟ'),
 (20.154866025084086, 'neighbourhood_ΠΡΟΜΠΟΝΑ'),
 (19.515846286101958, 'neighbourhood_ΑΝΩ ΠΑΤΗΣΙΑ'),
 (18.81684947757906, 'neighbourhood_ΕΛΛΗΝΟΡΩΣΩΝ'),
 (18.765080558781044, 'NearestStation_Ταύρος-Ελευθέριος Βενιζέλος'),
 (16.773760488409156, 'neighbourhood_ΡΗΓΙΛΛΗΣ'),
 (15.666650837677967, 'neighbourhood_ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ'),
 (12.801590589076488, 'neighbourhood_ΝΕΑ ΚΥΨΕΛΗ'),
 (10.729428021387914, 'neighbourhood_ΚΟΛΟΚΥΝΘΟΥ'),
 (10.661993392406485, 'neighbourhood_ΣΕΠΟΛΙΑ'),
 (7.464779888492062, 'neighbourhood_ΠΟΛΥΓΩΝΟ'),
 (6.005779048684808, 'nearestHoliday_Assumption of Mary to Heaven'),
 (5.3708049747226285, 'nearestHoliday_Ohi Day'),
 (5.287945892200381, 'property_type_Resort'),
 (5.176842297277206, 'nearestHoliday_Whit Monday'),
 (4.316373450490324, 'nearestHoliday_Clean Monday'),
 (4.271431610436922, 'property_type_Boat'),
 (3.5338571013388376, 'nearestHoliday_Annunciation'),
 (3.4468251835318626, 'nearestHoliday_Labour Day'),
 (3.3353867632691845, 'nearestHoliday_Pentecost'),
 (2.9300304832559, 'property_type_Bed and breakfast'),
 (2.5818532300654713, 'IsHoliday_True'),
 (2.581853229983699, 'IsHoliday_False'),
 (2.4334087257900916, 'nearestHoliday_Good Friday'),
 (2.2939637636866235, 'nearestHoliday_Epiphany'),
 (2.1293993889215708, 'NearestStation_Ταύρος'),
 (2.0802427540356896, 'nearestHoliday_Christmas Day'),
 (1.8678335887598672, 'property_type_casa particular'),
 (1.6551513054162013, 'nearestHoliday_Easter Monday'),
 (1.5897729951893969, 'nearestHoliday_Glorifying Mother of God'),
 (1.5784938959506298, 'nearestHoliday_Easter Sunday')]

In [ ]:
# Top 20 feature using tree based feature selection

# Fit a random forest regressor
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X, y)

# Get feature importances
importances = rf.feature_importances_

# Create a DataFrame to hold the results
feature_importances_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
})

# Sort the DataFrame by importance in descending order and reset index
sorted_features = feature_importances_df.sort_values(by='Importance', ascending=False).reset_index(drop=True)

# Display top features based on importance
print(sorted_features.head(20))

In [69]:
# Check for string errors -that was produced running RF feature selection

columns_to_check = ['minimum_nights', 'number_of_reviews', 'reviews_per_month',
                    'calculated_host_listings_count', 'availability_365',
                    'number_of_reviews_ltm', 'rating', 'bedrooms',
                    'beds', 'baths', 'MinDisplacement']

for col in columns_to_check:
    non_numeric_rows = df[pd.to_numeric(df[col], errors='coerce').isna()]
    if not non_numeric_rows.empty:
        print(f"Column: {col}")
        print(non_numeric_rows[col])

Column: rating
1597       1 bedroom
2272          Studio
2273          Studio
3521       1 bedroom
8493      2 bedrooms
             ...
461216           New
461217           New
461218           New
461219           New
461220           New
Name: rating, Length: 1249, dtype: object

In [70]:
df.isnull().sum()

neighbourhood                     0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
property_type                     0
city                              0
rating                            0
bedrooms                          0
beds                              0
baths                             0
MinDisplacement                   0
NearestStation                    0
IsHoliday                         0
holidayDateDiff                   0
nearestHoliday                    0
sentiment                         0
dtype: int64

In [71]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [72]:
df['rating'].isnull().sum()

1249

In [73]:
# We have 50,000 datasets.
# Drop with invalid ratings as it will not impact the dataset
df.dropna(subset=['rating'], inplace=True)

In [74]:
df.isnull().sum()

neighbourhood                     0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
property_type                     0
city                              0
rating                            0
bedrooms                          0
beds                              0
baths                             0
MinDisplacement                   0
NearestStation                    0
IsHoliday                         0
holidayDateDiff                   0
nearestHoliday                    0
sentiment                         0
dtype: int64

In [75]:
df_cat.isnull().sum()

price                                             0
neighbourhood_1Ο ΝΕΚΡΟΤΑΦΕΙΟ                      0
neighbourhood_ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ                    0
neighbourhood_ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ    0
neighbourhood_ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ                      0
                                                 ..
nearestHoliday_Labour Day                         0
nearestHoliday_New year                           0
nearestHoliday_Ohi Day                            0
nearestHoliday_Pentecost                          0
nearestHoliday_Whit Monday                        0
Length: 111, dtype: int64

In [76]:
X.isnull().sum()

neighbourhood_1Ο ΝΕΚΡΟΤΑΦΕΙΟ                      0
neighbourhood_ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ                    0
neighbourhood_ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ    0
neighbourhood_ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ                      0
neighbourhood_ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ                   0
                                                 ..
nearestHoliday_Labour Day                         0
nearestHoliday_New year                           0
nearestHoliday_Ohi Day                            0
nearestHoliday_Pentecost                          0
nearestHoliday_Whit Monday                        0
Length: 110, dtype: int64

In [77]:
X = pd.concat([df[['minimum_nights', 'number_of_reviews', 'reviews_per_month',
                   'calculated_host_listings_count', 'availability_365',
                   'number_of_reviews_ltm', 'rating', 'bedrooms',
                   'beds', 'baths', 'MinDisplacement',  
                   'holidayDateDiff', 'sentiment']],
               df_cat[df_cat.columns.difference(['price'])]], 
              axis=1)
y = df['price']

In [78]:
missing_data = X.isnull().mean()
columns_with_missing_data = missing_data[missing_data > 0]
print(columns_with_missing_data)

minimum_nights                    0.002708
number_of_reviews                 0.002708
reviews_per_month                 0.002708
calculated_host_listings_count    0.002708
availability_365                  0.002708
number_of_reviews_ltm             0.002708
rating                            0.002708
bedrooms                          0.002708
beds                              0.002708
baths                             0.002708
MinDisplacement                   0.002708
holidayDateDiff                   0.002708
sentiment                         0.002708
dtype: float64

In [79]:
X.shape

(461221, 123)

In [80]:
# Considering we have such a large dataset.
# Dropping 1249 rows is relatively small portion and dropping this fraction would not 
# not significantly reduce the volume of your dataset and is unlikely to lead to a loss of crucial information
# Thus, we can drop these rows

In [81]:
columns_with_missing_values = [
    'minimum_nights', 'number_of_reviews', 'reviews_per_month',
    'calculated_host_listings_count', 'availability_365', 'number_of_reviews_ltm',
    'rating', 'bedrooms', 'beds', 'baths', 'MinDisplacement', 'holidayDateDiff',
    'sentiment'
]

X.dropna(subset=columns_with_missing_values, inplace=True)

In [82]:
y = df['price']

In [83]:
X.shape

(459972, 123)

In [86]:
# Train the Extra Trees model
clf = ExtraTreesRegressor(n_estimators=50)
clf.fit(X, y)

# Pair feature names with their importance scores
features = list(zip(X.columns, clf.feature_importances_))

# Sort features based on importance
sorted_features = sorted(features, key=lambda x: x[1], reverse=True)

# Print the top 20 features
print("Extra Trees Top 20 Feature Importance:\n")
for feature, importance in sorted_features[:20]:
    print(f"{feature}: {importance}")

Extra Trees Top 20 Feature Importance:

baths: 0.2149945807304301
bedrooms: 0.09577073702052281
rating: 0.05749681723694658
beds: 0.05308546011866843
availability_365: 0.05018232058652909
number_of_reviews: 0.0430754959223738
number_of_reviews_ltm: 0.04013067028972908
calculated_host_listings_count: 0.03406911957611905
NearestStation_Ακρόπολη: 0.033768674343391834
neighbourhood_ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ: 0.032664647960777005
reviews_per_month: 0.03092140951875967
minimum_nights: 0.030248155906307535
MinDisplacement: 0.028494436392133525
room_type_Entire home/apt: 0.02567608644865466
neighbourhood_ΑΚΡΟΠΟΛΗ: 0.022240918918438664
property_type_Rental unit: 0.020457346072520415
NearestStation_Μοναστηράκι: 0.012724034345035742
property_type_Home: 0.01145298156551082
property_type_Boutique hotel: 0.010900832933329113
neighbourhood_ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ: 0.009648582560248564

In [87]:
pd.DataFrame(sorted_features).iloc[20].to_csv('extraTreesFeatureImportance.csv', index=False)

In [93]:
# Select variables automatically by weights and impurity based importance
model = SelectFromModel(clf, prefit=True)
X_new = model.transform(X)
X_new.shape

C:\Users\chimi\anaconda3\lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(

(459972, 24)

In [94]:
featureIdx = model.get_support()
featureNames = X.columns[featureIdx]
featureNames

Index(['minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'rating', 'bedrooms', 'beds', 'baths',
       'MinDisplacement', 'NearestStation_Ακρόπολη',
       'NearestStation_Μοναστηράκι', 'NearestStation_Σύνταγμα',
       'neighbourhood_ΑΚΡΟΠΟΛΗ', 'neighbourhood_ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ',
       'neighbourhood_ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ', 'property_type_Boutique hotel',
       'property_type_Condo', 'property_type_Home',
       'property_type_Rental unit', 'property_type_Serviced apartment',
       'property_type_Villa', 'room_type_Entire home/apt'],
      dtype='object')

In [95]:
# View the dataset in DataFrame
X_new = pd.DataFrame(X_new, columns=featureNames)

In [96]:
X_new.shape

(459972, 24)

In [99]:
# Scale the dataset
# Need to re-run this
# Previously it was scaled, but not this time.
# Not running again due to slow computer
# Minimmum_Nights are supposed have a default of 1
# Select the columns that need scaling
columns_to_scale = ['number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count',
                    'availability_365', 'number_of_reviews_ltm', 'rating', 'bedrooms', 'beds', 'baths', 'MinDisplacement']

# Instantiate the scaler
scaler = MinMaxScaler()

# Fit and transform the selected columns
X_new[columns_to_scale] = scaler.fit_transform(X_new[columns_to_scale])

# Now your selected columns are scaled within the range [0, 1]
# The categorical and binary columns remain unchanged

# Check the first few rows of the scaled data
print(X_new.head())

,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,rating,bedrooms,beds,baths,...,neighbourhood_ΑΚΡΟΠΟΛΗ,neighbourhood_ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,neighbourhood_ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,property_type_Boutique hotel,property_type_Condo,property_type_Home,property_type_Rental unit,property_type_Serviced apartment,property_type_Villa,room_type_Entire home/apt
0,0.0,0.0454,0.017042,0.055046,0.380822,0.041451,0.953678,0.090909,0.083333,0.222222,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0454,0.017042,0.055046,0.380822,0.041451,0.953678,0.090909,0.083333,0.222222,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0454,0.017042,0.055046,0.380822,0.041451,0.953678,0.090909,0.083333,0.222222,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0454,0.017042,0.055046,0.380822,0.041451,0.953678,0.090909,0.083333,0.222222,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0454,0.017042,0.055046,0.380822,0.041451,0.953678,0.090909,0.083333,0.222222,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [103]:
# Columns that will be used for the target variables
X_scaled_df.columns

Index(['minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'rating', 'bedrooms', 'beds', 'baths',
       'MinDisplacement', 'NearestStation_Ακρόπολη',
       'NearestStation_Μοναστηράκι', 'NearestStation_Σύνταγμα',
       'neighbourhood_ΑΚΡΟΠΟΛΗ', 'neighbourhood_ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ',
       'neighbourhood_ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ', 'property_type_Boutique hotel',
       'property_type_Condo', 'property_type_Home',
       'property_type_Rental unit', 'property_type_Serviced apartment',
       'property_type_Villa', 'room_type_Entire home/apt'],
      dtype='object')

In [105]:
# Modeling
X_scaled_df['reviews_per_month'].describe()

count    459972.000000
mean          0.219430
std           0.130788
min           0.000000
25%           0.117928
50%           0.203136
75%           0.299932
max           1.000000
Name: reviews_per_month, dtype: float64

In [ ]:
X_scaled_df.to_csv('X_scaled.csv', index=False)