In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# File path
file_path = "C:\\Users\\chimi\\Desktop\\Python Data Science Projects\\airbnb-rentalprice\\task3-eda\\athens_finalrental.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to check the data
print(df.head())

   listing_id                                               name  host_id  \
0       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
1       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
2       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
3       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177
4       10595  Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...    37177

  neighbourhood  latitude  longitude        room_type  price  minimum_nights  \
0   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
1   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
2   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
3   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1
4   ΑΜΠΕΛΟΚΗΠΟΙ  37.98863   23.76527  Entire home/apt    200               1

   number_of_reviews  ... number_of_reviews_ltm  reviewer_id        date  \
0                 41  ...                     8     189305.0  2011-05-20
1                 41  ...                     8     289831.0  2012-08-15
2                 41  ...                     8    2422327.0  2014-05-04
3                 41  ...                     8    2635427.0  2013-05-20
4                 41  ...                     8    5001999.0  2022-07-02

                                            comments  property_type    city  \
0  the apartment was wonderful fully equiped beau...          Condo  Athens
1  emmanouil was an excellent host he provided us...          Condo  Athens
2  our stay in emmanouil home was comfortable qui...          Condo  Athens
3  manos is a very good host he is kind and helpf...          Condo  Athens
4  highly recommend this apartment clean bright a...          Condo  Athens

  rating bedrooms beds baths
0   4.83      3.0  5.0   2.0
1   4.83      3.0  5.0   2.0
2   4.83      3.0  5.0   2.0
3   4.83      3.0  5.0   2.0
4   4.83      3.0  5.0   2.0

[5 rows x 24 columns]

In [3]:
df.duplicated().sum()

0

In [4]:
# Check for null values
df.isnull().mean()

listing_id                        0.000000
name                              0.000000
host_id                           0.000000
neighbourhood                     0.000000
latitude                          0.000000
longitude                         0.000000
room_type                         0.000000
price                             0.000000
minimum_nights                    0.000000
number_of_reviews                 0.000000
last_review                       0.000000
reviews_per_month                 0.000000
calculated_host_listings_count    0.000000
availability_365                  0.000000
number_of_reviews_ltm             0.000000
reviewer_id                       0.000000
date                              0.000000
comments                          0.000000
property_type                     0.000000
city                              0.000000
rating                            0.000000
bedrooms                          0.086828
beds                              0.000046
baths                             0.009811
dtype: float64

In [5]:
# Review the beds and 
df[df['bedrooms'].isna()]

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,...,number_of_reviews_ltm,reviewer_id,date,comments,property_type,city,rating,bedrooms,beds,baths
73,10993,Rental unit in Athens · ★4.84 · Studio · 2 bed...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.988880,23.764730,Entire home/apt,64,1,91,...,4,114526.0,2015-12-28,the studio is very nice and clean it has easy ...,Rental unit,Athens,4.84,NaN,2.0,1.0
74,10993,Rental unit in Athens · ★4.84 · Studio · 2 bed...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.988880,23.764730,Entire home/apt,64,1,91,...,4,482984.0,2015-12-30,mr emmanouil and niki are excellent hosts when...,Rental unit,Athens,4.84,NaN,2.0,1.0
75,10993,Rental unit in Athens · ★4.84 · Studio · 2 bed...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.988880,23.764730,Entire home/apt,64,1,91,...,4,1456656.0,2016-01-25,perfect hosting great area and emmanouil is re...,Rental unit,Athens,4.84,NaN,2.0,1.0
76,10993,Rental unit in Athens · ★4.84 · Studio · 2 bed...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.988880,23.764730,Entire home/apt,64,1,91,...,4,1773608.0,2021-11-06,cozy,Rental unit,Athens,4.84,NaN,2.0,1.0
77,10993,Rental unit in Athens · ★4.84 · Studio · 2 bed...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.988880,23.764730,Entire home/apt,64,1,91,...,4,3322748.0,2016-05-24,emmanouil is the perfect hostvery professional...,Rental unit,Athens,4.84,NaN,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460681,884280907531664596,Rental unit in Athina · ★New · Studio · 2 beds...,437864658,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.984187,23.737321,Entire home/apt,75,1,2,...,2,33225383.0,2023-06-05,great location and spacious and comfortable flat,Rental unit,Athina,New,NaN,2.0,1.0
460893,891127810465968720,Condo in Athina · ★New · Studio · 1 bed · 1 bath,514394288,ΚΥΨΕΛΗ,37.999338,23.741211,Entire home/apt,46,2,1,...,1,311890367.0,2023-06-08,loved staying at jkapartments such a clean cut...,Condo,Athina,New,NaN,1.0,1.0
461005,897436592980523653,Rental unit in Athina · ★New · Studio · 1 bed ...,47267002,ΠΕΔΙΟ ΑΡΕΩΣ,37.994173,23.732770,Entire home/apt,80,3,1,...,1,4059287.0,2023-06-12,the apartment is perfectly located not directl...,Rental unit,Athina,New,NaN,1.0,1.0
461190,909865477455399540,Rental unit in Athina · ★New · Studio · 3 beds...,465170894,ΝΕΟΣ ΚΟΣΜΟΣ,37.964657,23.728956,Entire home/apt,71,2,1,...,1,35459020.0,2023-06-18,george and his team are great hosts the checki...,Rental unit,Athina,New,NaN,3.0,1.0
461205,912974240901958910,Rental unit in Athina · ★New · Studio · 1 bed ...,165767990,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.984752,23.740757,Entire home/apt,86,2,1,...,1,89791146.0,2023-06-19,highly recommended,Rental unit,Athina,New,NaN,1.0,1.0

In [6]:
# BAthrooms 
df[df['beds'].isna()]

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,...,number_of_reviews_ltm,reviewer_id,date,comments,property_type,city,rating,bedrooms,beds,baths
264603,27448165,Serviced apartment in Athina · 1 bedroom · 2 beds,206838334,ΘΗΣΕΙΟ,37.978050,23.722880,Hotel room,261,1,2,...,0,29111261.0,2021-08-31,excellent location great value for money and s...,Serviced apartment,Athina,1 bedroom,2.0,NaN,NaN
264604,27448165,Serviced apartment in Athina · 1 bedroom · 2 beds,206838334,ΘΗΣΕΙΟ,37.978050,23.722880,Hotel room,261,1,2,...,0,236495205.0,2021-08-11,amazing location with buzz of the downtown lif...,Serviced apartment,Athina,1 bedroom,2.0,NaN,NaN
331961,34144987,Rental unit in Athens · Studio · 1 bath,1585338,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.986870,23.742170,Entire home/apt,61,5,1,...,1,62734525.0,2022-07-29,good area where mostly locals hang outbrbut al...,Rental unit,Athens,Studio,1.0,NaN,NaN
331962,34144991,Rental unit in Athens · Studio · 1 bath,1585338,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.988250,23.742850,Entire home/apt,61,5,2,...,0,381541140.0,2022-04-10,i was pleasantly surprised by the quality of t...,Rental unit,Athens,Studio,1.0,NaN,NaN
361279,38516893,Rental unit in Athens · 1 bedroom · 2 baths,556615,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,37.985250,23.729200,Entire home/apt,170,2,1,...,0,295332221.0,2019-09-25,miglen your flat is very nice everything was g...,Rental unit,Athens,1 bedroom,2.0,NaN,NaN
372795,40977090,Rental unit in Athina · 2 bedrooms · 1.5 baths,75367164,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.984800,23.735970,Entire home/apt,139,3,2,...,2,435561898.0,2022-07-28,the perfect place to stay in athens,Rental unit,Athina,2 bedrooms,1.0,NaN,NaN
383579,43501418,Rental unit in Athina · 1 bedroom · 1 bath,47243951,ΠΛΑΤΕΙΑ ΑΜΕΡΙΚΗΣ,37.999590,23.732540,Private room,20,120,2,...,2,455334905.0,2023-02-11,de host was vriendelijk en reageerde snel de k...,Rental unit,Athina,1 bedroom,1.0,NaN,NaN
384058,43608276,Rental unit in Athina · 1 bedroom · 2 shared b...,47243951,ΠΑΤΗΣΙΑ,38.012990,23.733810,Private room,20,120,1,...,1,226556743.0,2022-07-26,great stay a good place to spend time in athens,Rental unit,Athina,1 bedroom,2.0,NaN,NaN
384473,43662192,Tiny home in Athina · 1 bed · 1 bath,5405197,ΛΥΚΑΒΗΤΤΟΣ,37.983310,23.741760,Entire home/apt,46,3,2,...,0,176831720.0,2020-08-31,the appartement was awesome well equiped and c...,Tiny home,Athina,1 bed,1.0,NaN,NaN
384474,43662192,Tiny home in Athina · 1 bed · 1 bath,5405197,ΛΥΚΑΒΗΤΤΟΣ,37.983310,23.741760,Entire home/apt,46,3,2,...,0,343402687.0,2020-08-16,the best airbnb stay we had brmy boyfriend and...,Tiny home,Athina,1 bed,1.0,NaN,NaN
386038,43879292,Rental unit in Athina · 2 bedrooms · 1 bath,187720552,ΝΙΡΒΑΝΑ,38.012220,23.728540,Entire home/apt,49,4,1,...,0,376741935.0,2021-06-21,hope to come again,Rental unit,Athina,2 bedrooms,1.0,NaN,NaN
406965,50004688,Rental unit in Athina · 1 bedroom · 2 shared b...,47243951,ΠΑΤΗΣΙΑ,38.011020,23.735620,Private room,20,30,1,...,1,95077291.0,2022-07-22,this is one listing that looks exactly like in...,Rental unit,Athina,1 bedroom,2.0,NaN,NaN
411202,50474441,Condo in Athina · 1 bedroom · 1.5 shared baths,47243951,ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ,37.993600,23.730390,Private room,20,120,1,...,1,364480461.0,2022-08-11,very nice apartment always good roommates and ...,Condo,Athina,1 bedroom,1.0,NaN,NaN
425466,53620829,Boutique hotel in Athina · 1 bedroom · 1 priva...,5701515,ΓΟΥΔΙ,37.985889,23.761471,Private room,150,1,2,...,2,242537046.0,2022-10-08,as a first time visitor to athens greece the a...,Boutique hotel,Athina,1 bedroom,1.0,NaN,NaN
425467,53620829,Boutique hotel in Athina · 1 bedroom · 1 priva...,5701515,ΓΟΥΔΙ,37.985889,23.761471,Private room,150,1,2,...,2,297725529.0,2023-03-22,honestly best place i ve stayed on airbnb chec...,Boutique hotel,Athina,1 bedroom,1.0,NaN,NaN
445336,651804194123453340,Rental unit in Athina · Studio · 1 shared bath,2089542,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,37.961320,23.720890,Private room,34,1,1,...,1,374222080.0,2023-05-18,i definitely recommend staying at any of tia a...,Rental unit,Athina,Studio,1.0,NaN,NaN
445337,651805902680429381,Rental unit in Athina · Studio · 1 private bath,2089542,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,37.962970,23.720570,Private room,42,1,1,...,1,45365376.0,2022-07-04,lappartement se situe dans le quartier de veik...,Rental unit,Athina,Studio,1.0,NaN,NaN
454088,749753687109876471,Condo in Athina · 2 bedrooms · 2 baths,9428336,ΑΜΠΕΛΟΚΗΠΟΙ,37.990745,23.757310,Entire home/apt,81,2,2,...,2,218728101.0,2022-12-04,the flat is very spacious and has everything w...,Condo,Athina,2 bedrooms,2.0,NaN,NaN
454434,755531239101482479,Rental unit in Athina · 1 bedroom · 2 beds · H...,486848590,ΚΟΛΩΝΟΣ,37.991340,23.716970,Entire home/apt,50,2,2,...,2,513975453.0,2023-05-15,10,Rental unit,Athina,1 bedroom,2.0,NaN,NaN
456685,802102955876824965,Rental unit in Athina · 1 bedroom · 1 bath,89859710,ΠΑΓΚΡΑΤΙ,37.969071,23.751246,Entire home/apt,48,1,2,...,2,427603398.0,2023-01-23,br 10 br br,Rental unit,Athina,1 bedroom,1.0,NaN,NaN
457378,815755603629062668,Rental unit in Athina · 1 bedroom · 2 beds · H...,498671241,ΓΟΥΒΑ,37.956231,23.741929,Entire home/apt,43,1,1,...,1,432789513.0,2023-05-07,zona tranquila y cerca de todo no tuve buena a...,Rental unit,Athina,1 bedroom,2.0,NaN,NaN

In [7]:
df[df['baths'].isna()]

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,...,number_of_reviews_ltm,reviewer_id,date,comments,property_type,city,rating,bedrooms,beds,baths
1597,251361,Rental unit in Galatsi · 1 bedroom · 1 bed · 1...,592616,ΑΝΩ ΠΑΤΗΣΙΑ,38.018730,23.74465,Entire home/apt,138,5,1,...,0,4010322.0,2013-05-23,what a lovely apartment my husband baby toddle...,Rental unit,Galatsi,1 bedroom,1.0,1.0,NaN
2272,308157,Rental unit in Athens · Studio · 1 bed · 1 bath,1585338,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.987290,23.74311,Entire home/apt,65,5,2,...,0,3636258.0,2015-06-04,flavia was the most charming hostbreverything ...,Rental unit,Athens,Studio,1.0,1.0,NaN
2273,308157,Rental unit in Athens · Studio · 1 bed · 1 bath,1585338,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.987290,23.74311,Entire home/apt,65,5,2,...,0,6268705.0,2016-04-05,flavia vas very kind host and very responsive ...,Rental unit,Athens,Studio,1.0,1.0,NaN
3521,478626,Bed and breakfast in Athens · 1 bedroom · 1 be...,2370772,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,37.978430,23.72564,Entire home/apt,120,1,1,...,0,31765116.0,2015-06-12,the host canceled this reservation the day bef...,Bed and breakfast,Athens,1 bedroom,1.0,1.0,NaN
8493,767272,Home in Athens · 2 bedrooms · 1 bed · 3.5 baths,964919,ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ,37.984470,23.72112,Entire home/apt,350,3,2,...,0,4365541.0,2014-10-28,very comfortable house in a unique part of ath...,Home,Athens,2 bedrooms,1.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460916,891727835665347371,Rental unit in Athina · ★4.50 · 1 bedroom · 1 ...,277722023,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,37.980020,23.72596,Entire home/apt,63,4,6,...,6,262085849.0,2023-05-20,le studio est petit comme sur les photos mais ...,Rental unit,Athina,4.50,1.0,1.0,NaN
460917,891727835665347371,Rental unit in Athina · ★4.50 · 1 bedroom · 1 ...,277722023,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,37.980020,23.72596,Entire home/apt,63,4,6,...,6,394349354.0,2023-06-01,good location bed hard to get into,Rental unit,Athina,4.50,1.0,1.0,NaN
460987,896264512176491832,Rental unit in Athina · ★5.0 · 2 bedrooms · 1....,204301874,ΝΕΟΣ ΚΟΣΜΟΣ,37.964757,23.72830,Entire home/apt,85,3,4,...,4,6184572.0,2023-06-12,we had a wonderful stay great location and bea...,Rental unit,Athina,5.0,2.0,1.0,NaN
460988,896264512176491832,Rental unit in Athina · ★5.0 · 2 bedrooms · 1....,204301874,ΝΕΟΣ ΚΟΣΜΟΣ,37.964757,23.72830,Entire home/apt,85,3,4,...,4,106959987.0,2023-06-08,loved the house and the area is super close to...,Rental unit,Athina,5.0,2.0,1.0,NaN
460989,896264512176491832,Rental unit in Athina · ★5.0 · 2 bedrooms · 1....,204301874,ΝΕΟΣ ΚΟΣΜΟΣ,37.964757,23.72830,Entire home/apt,85,3,4,...,4,516463863.0,2023-05-29,it is my first time at joelle s apartment a gr...,Rental unit,Athina,5.0,2.0,1.0,NaN

In [8]:
# Some properties or listing could be studio apartments so for bedrooms-fill the NA with 0

df['bedrooms'].fillna(0, inplace=True)

In [9]:
# It does not seem logical for properties to have 0 beds and 0 baths
# Using the median

In [10]:
df.columns

Index(['listing_id', 'name', 'host_id', 'neighbourhood', 'latitude',
       'longitude', 'room_type', 'price', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'reviewer_id', 'date', 'comments',
       'property_type', 'city', 'rating', 'bedrooms', 'beds', 'baths'],
      dtype='object')

In [12]:
# Instead of using KNN-imputation/ Using median due to computational limitation on my labtop
df['beds'].fillna(df['beds'].median(), inplace=True)
df['baths'].fillna(df['baths'].median(), inplace=True)

In [13]:
df.isnull().sum()

listing_id                        0
name                              0
host_id                           0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
reviewer_id                       0
date                              0
comments                          0
property_type                     0
city                              0
rating                            0
bedrooms                          0
beds                              0
baths                             0
dtype: int64

In [14]:
df.head()

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,...,number_of_reviews_ltm,reviewer_id,date,comments,property_type,city,rating,bedrooms,beds,baths
0,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,8,189305.0,2011-05-20,the apartment was wonderful fully equiped beau...,Condo,Athens,4.83,3.0,5.0,2.0
1,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,8,289831.0,2012-08-15,emmanouil was an excellent host he provided us...,Condo,Athens,4.83,3.0,5.0,2.0
2,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,8,2422327.0,2014-05-04,our stay in emmanouil home was comfortable qui...,Condo,Athens,4.83,3.0,5.0,2.0
3,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,8,2635427.0,2013-05-20,manos is a very good host he is kind and helpf...,Condo,Athens,4.83,3.0,5.0,2.0
4,10595,Condo in Athens · ★4.83 · 3 bedrooms · 5 beds ...,37177,ΑΜΠΕΛΟΚΗΠΟΙ,37.98863,23.76527,Entire home/apt,200,1,41,...,8,5001999.0,2022-07-02,highly recommend this apartment clean bright a...,Condo,Athens,4.83,3.0,5.0,2.0